force-app/main/default/objects/Client__c/fields/Client_Email__c.field-meta.xml
<CustomField>
    <fullName>Client_Email__c</fullName>
    <label>Client Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Customer_Notified_At__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notified_At__c</fullName>
    <label>Customer Notified At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <label>Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Customer Notified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailBatchHelperClass.cls
public with sharing class SendEmailBatchHelperClass {
    
    public static Map<String,Map<String,List<Document__c>>> createClientToTypeWiseDocumentMap(List<Document__c> scope){
        Map<String,Map<String,List<Document__c>>> clientToTypeDocumentMap = new Map<String,Map<String,List<Document__c>>>(); 
        for(Document__c s : scope){
            if(clientToTypeDocumentMap.containsKey(s.Client__r.Client_Email__c)){
                Map<String,List<Document__c>> typeToDocMap = clientToTypeDocumentMap.get(s.Client__r.Client_Email__c);
                if(typeToDocMap.containsKey(s.Type__c)){
                    typeToDocMap.get(s.Type__c).add(s);       
                }else{
                    typeToDocMap.put(s.Type__c,new List<Document__c>{s});
                }
                clientToTypeDocumentMap.put(s.Client__r.Client_Email__c,typeToDocMap);
            }else {
                Map<String,List<Document__c>> typeToDocMap = new Map<String,List<Document__c>>();
                typeToDocMap.put(s.Type__c,new List<Document__c>{s});
                clientToTypeDocumentMap.put(s.Client__r.Client_Email__c,typeToDocMap);
            }
        }
        System.debug('clientToTypeDocumentMap Helper:'+clientToTypeDocumentMap);
        if(clientToTypeDocumentMap.isEmpty()){
            return null;
        }
        return clientToTypeDocumentMap;
    }

    public static void setNotificationStatus(List<Document__c> scope){
        List<Document__c> updatedDocuments = new List<Document__c> ();
        for(Document__c document : scope){
            document.Notification_Status__c = 'Customer Notified';
            document.Customer_Notified_At__c = System.now();
            updatedDocuments.add(document);
        }
        Database.update(updatedDocuments,false);
    }

    public static Messaging.SingleEmailMessage getSingleEmailMessage(String emailBody, String toAddress, String subject){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setHtmlBody(emailBody);
        mail.setToAddresses(new String[] { UserInfo.getUserEmail()});
        mail.setSenderDisplayName('Batch Processing');
        mail.setSubject(subject);
        return mail;
    }
    // public static Messaging.SingleEmailMessage createEmail(List<String> documentTypeList){
    //     for(String docType : documentTypeList){
    //         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    //         Map<String,List<Document__c>> documentType = clientToTypeDocumentMap.get(eachClient);
    //         System.debug('docType :'+docType);
    //         String Message = 'Hello Customer, <br/>';
    //         Message += 'A new document : New Document has be uploaded to your portfolio. <br/>';
    //         Message += 'Document Type : ' + docType +'<br/>';        
    //         Message += 'Thanks <br/>';
    //         Message += 'Middas Wealth Management';
    //         mail.setHtmlBody(Message);
    //         mail.setToAddresses(new String[] {eachClient});
    //         mail.setReplyTo('manalijadhav97@gmail.com');
    //         mail.setSenderDisplayName('Batch Processing');
    //         mail.setSubject('New Document : Middas Wealth Management');
    //         //mail.setPlainTextBody('Batch Process has completed');
    //         system.debug('mail:'+mail);
    //         //mailList.add(mail);
    //     }
    // }
}