force-app/main/default/objects/Client__c/fields/Client_Email__c.field-meta.xml
<CustomField>
    <fullName>Client_Email__c</fullName>
    <label>Client Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Customer_Notified_At__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notified_At__c</fullName>
    <label>Customer Notified At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Generation_Date__c.field-meta.xml
<CustomField>
    <fullName>Generation_Date__c</fullName>
    <label>Generation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <label>Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Customer Notified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailBatchClass.cls
/**
 * @description       : The batch runs every 8 hours and sends notifications to clients
 * @last modified on  : 07-13-2023
**/
public with sharing class SendEmailBatchClass implements Database.Batchable<sObject>,Database.RaisesPlatformEvents{

    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id,Name,Type__c,Notification_Status__c,Generation_Date__c,Customer_Notified_At__c,Client__r.Client_Email__c FROM Document__c WHERE Notification_Status__c=\'New\' ORDER BY Client__r.Client_Email__c';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Document__c> scope){
        try{
            Map<String,Map<String,List<Document__c>>> clientToTypeDocumentMap = SendEmailBatchHelperClass.createClientToTypeWiseDocumentMap(scope);

            List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();

            Set<Id> documentIds = new Set<Id>();
            // get files related to documents 
            for(Document__c doc : scope) {
                documentIds.add(doc.Id);
            }
            
            Map<Id, Id> documentIdToContentDocumentId = new Map<Id,Id>();
            for(ContentDocumentLink cdLink : [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN : documentIds LIMIT 50000]){
                documentIdToContentDocumentId.put(cdLink.ContentDocumentId, cdLink.LinkedEntityId);
            }

            Map<Id, ContentVersion> docIdToContentVersion = new Map<Id, ContentVersion>();
            for(ContentVersion cntVersion : [SELECT Title, FileExtension, ContentDocumentId,VersionData FROM ContentVersion WHERE ContentDocumentId IN : documentIdToContentDocumentId.keySet() LIMIT 50000]){
                docIdToContentVersion.put(documentIdToContentDocumentId.get(cntVersion.ContentDocumentId), cntVersion);
            }

            for(String clientEmail : clientToTypeDocumentMap.keySet()){
                Map<String, List<Document__c>> typeWiseDocs = clientToTypeDocumentMap.get(clientEmail);
                for(String docType : typeWiseDocs.keySet()){
                    String subject = getSubject(docType);
                    String emailBody = getEmailBody(typeWiseDocs.get(docType));
                    List<Messaging.EmailFileAttachment> attachments = getEmailAttachments(typeWiseDocs.get(docType), docIdToContentVersion);
                    mailList.add(SingleEmailService.getSingleEmailMessage(emailBody, clientEmail, subject, 'Midas Wealth', attachments));
                }
            }

            // send emails
            Messaging.sendEmail(mailList);

            // set the nofication on Document__c record
            SendEmailBatchHelperClass.setNotificationStatus(scope);

        }catch(Exception e){
            System.debug('Exception :'+  e.getCause() + e.getStackTraceString() + e.getMessage());
        }   
    }
    public void finish(Database.BatchableContext BC){
        
    }

    public static String getSubject(String docType){
        return 'New ' + docType + ' Documents Uploladed to Midas';
    }
    
    public static String getEmailBody(List<Document__c> documents){
        String emailBody = 'Hi! The following documents have been uploaded.\n';
        for(Document__c doc : documents){
            emailBody +=doc.Name +'\n';
        }
        emailBody += 'Thanks <br/>';
        emailBody += 'Middas Wealth Management';
        return emailBody;
    }

    public static List<Messaging.EmailFileAttachment> getEmailAttachments(List<Document__c> documents, Map<Id, ContentVersion> docIdToContentVersion){
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
        for(Document__c document : documents) {

            if(!docIdToContentVersion.containsKey(document.Id)){
                return new List<Messaging.EmailFileAttachment>();
            }

            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            ContentVersion cntVersion = docIdToContentVersion.get(document.Id);
            attachment.setFileName(cntVersion.Title);
            attachment.setBody(cntVersion.VersionData);
            attachments.add(attachment);
        }
        return attachments;
    }
}

// Calculation 
// No of users - 4000
// no of docu type - 4
// maximum no of emails to send - 16000 *