force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <label>Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Customer Notified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailBatchTest.cls
@IsTest
public with sharing class SendEmailBatchTest {
    
    @IsTest
    static void setupTestData(){
        
        List<Document__c> documentList = new List<Document__c>();
        for(Integer i=0 ;i <5;i++)
        {
            Document__c doc = new Document__c();
            doc.Name ='Name'+i;
            doc.Type__c = 'Report';
            doc.Notification_Status__c = 'New';
            documentList.add(doc);
        }
        for(Integer i=0 ;i <5;i++)
        {
            Document__c doc = new Document__c();
            doc.Name ='Name'+i;
            doc.Type__c = 'Transactional';
            doc.Notification_Status__c = 'New';
            documentList.add(doc);
        }
        for(Integer i=0 ;i <5;i++)
        {
            Document__c doc = new Document__c();
            doc.Name ='Name'+i;
            doc.Type__c = 'Legal';
            doc.Notification_Status__c = 'New';
            documentList.add(doc);
        }
        for(Integer i=0 ;i <5;i++)
        {
            Document__c doc = new Document__c();
            doc.Name ='Name'+i;
            doc.Type__c = 'Contract';
            doc.Notification_Status__c = 'New';
            documentList.add(doc);
        }
        
        insert documentList;
        
    }
     @IsTest
    static void testBatch(){
        
        Test.startTest();
        setupTestData();
        SendEmailBatchClass obj = new SendEmailBatchClass();
        DataBase.executeBatch(obj); 
        Test.stopTest();
        
    }

}